
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"   # Port HTTP pour distribuer le certificat CA
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/html:/usr/share/nginx/html/cap-epac:ro  # guide HTML