
listening-ip=0.0.0.0
listening-port=3478
tls-listening-port=5349


relay-ip=192.168.100.195
external-ip=192.168.100.195


min-port=49152
max-port=65535


user=cap-epac:CapEpacTurn2025


static-auth-secret=CapEpacTurnSecret2025LAN

# Durée de validité des credentials (24h)
credential-lifetime=86400

no-tcp-relay

# Activer UDP et TCP pour les clients
lt-cred-mech

AN
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
# Autoriser le sous-réseau LAN (à adapter)
allowed-peer-ip=192.168.100.0-192.168.100.255
allowed-peer-ip=127.0.0.1

log-file=/var/log/coturn/turnserver.log
verbose
no-stdout-log

realm=cap-epac.local

max-allocate-lifetime=3600
channel-lifetime=600
permission-lifetime=300
stale-nonce=600

no-multicast-peers
no-rfc5780
no-stun-backward-compatibility
response-origin-only-with-rfc5780
